"""empty message

Revision ID: 43b521a5461a
Revises: 402c4b6e91e7
Create Date: 2021-03-02 22:44:20.537243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b521a5461a'
down_revision = '402c4b6e91e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('name', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'name')
    # ### end Alembic commands ###
