"""empty message

Revision ID: 6cb097f2c171
Revises: 96e323930f6b
Create Date: 2021-02-25 21:49:15.795834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cb097f2c171'
down_revision = '96e323930f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('favorites_id', sa.Integer(), nullable=True))
    op.drop_constraint('favorites_ibfk_1', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'user', ['favorites_id'], ['id'])
    op.drop_column('favorites', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_ibfk_1', 'favorites', 'user', ['user_id'], ['id'])
    op.drop_column('favorites', 'favorites_id')
    # ### end Alembic commands ###
